version: '3.3'

# Sample database setup with docker, update JDBC settings to reflect your settings here.

services:
  db:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_DATABASE: 'lyrasis'
      MYSQL_USER: 'lyrasis_capture'
      MYSQL_PASSWORD: 'placeholder'
      MYSQL_ROOT_PASSWORD: 'placeholder'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /Users/joey/lyrasis/mysql:/var/lib/mysql

